language: julia

os:
  - linux
  - osx

julia:
  - 0.7
  - 1.0
  - nightly

matrix:
  allow_failures:
    - julia: nightly

addons:
  apt_packages:
    - gfortran
branches:
  only:
    - master
script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    wget --no-check-certificate http://www.cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz;
    tar -xzf cmake-3.3.2-Linux-x86_64.tar.gz;
    sudo cp -fR cmake-3.3.2-Linux-x86_64/* /usr;
    export PATH=`pwd`/cmake-3.3.2-Linux-x86_64/bin:$PATH; fi
  - which cmake
  - cmake --version
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd())'
  - julia --check-bounds=yes -e 'Pkg.build("AmplNLReader"); Pkg.test("AmplNLReader"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("AmplNLReader")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
