name = "AmplNLReader"
uuid = "77dd3d4c-cb1d-5e09-9340-85030ff7ba66"
version = "0.12.2"

[deps]
ASL_jll = "ae81ac8f-d209-56e5-92de-9978fef736f9"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
ASL_jll = "0.1.3"
Libdl = "1.10"
NLPModels = "0.21.6"
SparseArrays = "1.10"
julia = "1.10"
