[deps]
ASL_jll = "ae81ac8f-d209-56e5-92de-9978fef736f9"
Clang = "40e3b903-d033-50b4-a0cc-940c62c95e31"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"

[compat]
ASL_jll = "0.1.3"
julia = "1.10"
